Public Bootstrap4CSS As String
Public Bootstrap4JS As String
Public popperJS As String
Public jQueryJS As String



Private Sub Class_Initialize()
'CSS
Bootstrap4CSS = "https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"

'JS
Bootstrap4JS = "https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
popperJS = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"
jQueryJS = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"


End Sub
