<script type='text/javascript'>
  window.onload = function () {
    
	
	
	var chart = new CanvasJS.Chart('chartContainer',
    {
		interactivityEnabled: true, 
		animationEnabled: true,
		animationDuration: 1200,
		exportFileName: 'Range Spline Area',
		exportEnabled: true,
		zoomEnabled:true,
		zoomType: 'xy',
		theme: 'light2', //'light1', 'dark1', 'dark2'
		backgroundColor: '#F5DEB3',
		
		width: 320,
		height: 260,
		dataPointMaxWidth: 20,
		dataPointMinWidth: 2,
		dataPointWidth: 20,
		
		
		title:{
			text: 'This is a Chart Title',
			wrap: false,
			maxWidth: 200,
			dockInsidePlotArea: true,
			verticalAlign: 'center',
			horizontalAlign: 'right',
			fontSize: 30,
			fontFamily: 'tahoma',
			fontWeight: 'bold',
			fontColor: 'red',
			fontStyle: 'italic',
			borderThickness: 2,
			cornerRadius: 4,
			borderColor: 'green',
			backgroundColor: '#f4d5a6',
			margin: 10,
			padding: 2,
		},
    
		CanvasJS.addColorSet('customColorSet1',
		[//colorSet Array
		 '#4661EE',
		 '#EC5657',
		 '#1BCDD1',
		 '#8FAABB',
		 '#B08BEB',
		 '#3EA0DD',
		 '#F5A52A',
		 '#23BFAA',
		 '#FAA586',
		 '#EB8CC6',
		]);

		subtitles:[
		  {// subtitle 1
		  },
		 
		  {// subtitle 2
		  },
		 
		 ],
		});
		axisX:{
			title:'Axis X title',
			titleWrap: false,
			titleMaxWidth:200,
			titleFontColor: 'red',
			titleFontSize: 35,
			titleFontFamily: 'verdana',
			titleFontWeight: 'bold',
			fontStyle: 'italic',
			margin: 10,
			labelBackgroundColor:'black',
			labelMaxWidth: 20,
			labelMaxWidth: 50, 
			labelWrap: true,
			labelAutoFit: true,
			labelAngle: 180,
			labelFontFamily: 'tahoma',
			labelFontColor: 'red',
			labelFontSize: 20,
			labelFontWeight: 'bold',
			labelFontStyle: 'italic',
			prefix: 'batch ', 
			suffix: ' times', 
			valueFormatString: '#,##0.##',
			minimum: 0,
			maximum: 150,
			viewportMinimum: -50,
			viewportMaximum: 50,
			interval: 50,
			intervalType: 'month',
			reversed:  true,
			logarithmic:  true,
			logarithmBase:  2,
			tickLength: 5,
			tickColor: 'black',
			tickThickness: 1,
			lineColor: 'black',
			lineThickness: 3,
			lineDashType: 'solid',
			gridDashType: 'solid',
			gridThickness: 1,
			interlacedColor: '#FEFDDF'
			gridColor: 'black',
		},
		
		axisY:{
			title:'Axis Y Title',
			titleMaxWidth:200,
			titleWrap: false,
			titleFontColor: 'red',
			titleFontSize: 5,
			titleFontFamily: 'verdana',
			titleFontWeight: 'bold',
			fontStyle: 'italic',
			margin: 10,
			labelBackgroundColor:'black',
			labelMaxWidth: 50,
			labelMaxWidth: 50,
			labelAutoFit: true,
			labelAngle: 180,
			labelFontFamily: 'tahoma',
			labelFontColor: 'black',
			labelFontSize: 20,
			labelFontWeight: 'bold',
			labelFontStyle: 'italic',
			prefix: '$',
			suffix: ' USD',
			valueFormatString: '#,##0.##'
			minimum: 150,
			maximum: 150,
			interval: 50,
			reversed:  true,
			logarithmic:  true,
			logarithmBase:  2,
			viewportMinimum: -50,
			viewportMaximum: 50.
			tickLength: 5,
			tickColor: 'black',
			tickThickness: 5,
			lineColor: 'black',
			lineThickness: 1,
			lineDashType: 'solid',
			gridDashType: 'solid',
			interlacedColor: '#FEFDDF',
			gridThickness: 1,
			gridColor: 'orange',
			includeZero: true,
		},
		
		axisX2:{
			title:'Axis X title',
			titleWrap: false,
			titleMaxWidth:200,
			titleFontColor: 'red',
			titleFontSize: 35,
			titleFontFamily: 'verdana',
			titleFontWeight: 'bold',
			fontStyle: 'italic',
			margin: 10,
			labelBackgroundColor:'black',
			labelMaxWidth: 20,
			labelMaxWidth: 50, 
			labelWrap: true,
			labelAutoFit: true,
			labelAngle: 180,
			labelFontFamily: 'tahoma',
			labelFontColor: 'red',
			labelFontSize: 20,
			labelFontWeight: 'bold',
			labelFontStyle: 'italic',
			prefix: 'batch ', 
			suffix: ' times', 
			valueFormatString: '#,##0.##',
			minimum: 0,
			maximum: 150,
			viewportMinimum: -50,
			viewportMaximum: 50,
			interval: 50,
			intervalType: 'month',
			reversed:  true,
			logarithmic:  true,
			logarithmBase:  2,
			tickLength: 5,
			tickColor: 'black',
			tickThickness: 1,
			lineColor: 'black',
			lineThickness: 3,
			lineDashType: 'solid',
			gridDashType: 'solid',
			gridThickness: 1,
			interlacedColor: '#FEFDDF'
			gridColor: 'black',
		},
		
		axisY2:{
			title:'Axis Y Title',
			titleMaxWidth:200,
			titleWrap: false,
			titleFontColor: 'red',
			titleFontSize: 5,
			titleFontFamily: 'verdana',
			titleFontWeight: 'bold',
			fontStyle: 'italic',
			margin: 10,
			labelBackgroundColor:'black',
			labelMaxWidth: 50,
			labelMaxWidth: 50,
			labelAutoFit: true,
			labelAngle: 180,
			labelFontFamily: 'tahoma',
			labelFontColor: 'black',
			labelFontSize: 20,
			labelFontWeight: 'bold',
			labelFontStyle: 'italic',
			prefix: '$',
			suffix: ' USD',
			valueFormatString: '#,##0.##'
			minimum: 150,
			maximum: 150,
			interval: 50,
			reversed:  true,
			logarithmic:  true,
			logarithmBase:  2,
			viewportMinimum: -50,
			viewportMaximum: 50.
			tickLength: 5,
			tickColor: 'black',
			tickThickness: 5,
			lineColor: 'black',
			lineThickness: 1,
			lineDashType: 'solid',
			gridDashType: 'solid',
			interlacedColor: '#FEFDDF',
			gridThickness: 1,
			gridColor: 'orange',
			includeZero: true,
		},
		
		legend:{
			cursor: 'pointer',
			reversed: true,
			maxWidth: 200,
			maxHeight: 200,
			itemWrap: false,
			itemMaxWidth: 200,
			itemWidth: 200,
			markerMargin: 4,
			dockInsidePlotArea: false 
			fontSize: 30,
			fontFamily: 'tahoma',
			fontColor: 'black',
			fontWeight: 'bold',
			fontStyle: 'italic',
			verticalAlign: 'center',
			horizontalAlign: 'right',
			itemclick: toggleDataSeries,
		},
		
		toolTip:{
			enabled: true,	
			fontColor: 'black',
			fontStyle: 'italic',
			fontSize: 30,
			fontFamily: 'tahoma',
			fontweight: 'bold',
			borderThickness: 1,
			cornerRadius: 4,
			reversed: true,
			shared: true,
			backgroundColor: '#f4d5a6',
			content:'x: {x}, y: {y}' ,
			animationEnabled: true,
			borderColor: 'white',
		},
			
		data:[
			cursor: 'pointer',
			axisXType: 'secondary'
			axisYType: 'secondary',
			axisXIndex: 1, 
			axisYIndex: 1, 
			xValueType: 'dateTime', //'number', 'dateTime'
			yValueFormatString: '$####.00',
			zValueFormatString: '##.#0 mm',
			percentFormatString: '#0.##',
			xValueFormatString: "Year ####",
			highlightEnabled: true,
			indexLabelLineDashType: 'solid',
			startAngle:  90,
			indexLabel: '{x}, {y}',
			radius:  '90%', 
			innerRadius: '70%',
			indexLabelPlacement: 'inside',
			indexLabelMaxWidth: 20,
			indexLabelWrap: true,
			indexLabelOrientation: 'vertical',
			neckWidth:  '20%',
			indexLabelBackgroundColor: 'yellow',
			neckHeight:  '40%',
			indexLabelFontStyle: 'italic',
			reversed: true,
			valueRepresents: 'area', 
			indexLabelFontFamily: 'tahoma',
			stemColor: '#BB2286',
			stemThickness: 4,
			indexLabelFontWeight: 'bold',
			indexLabelLineColor: 'green',
			stemDashType : 'dash',
			indexLabelLineThickness: 5,
			toolTipContent: "{y} sales",
			linkedDataSeriesIndex: 1,
			explodeOnClick: false,
			
			
			//By Chart Layer
			type : 'area',
			name: 'year 2005',
			visible: false,
			lineDashType: 'solid',
			color: 'red',
			lineColor: 'red',
			bevelEnabled: true,
			fillOpacity: .3, 
			upperBoxColor: '#DD7E86',
			lowerBoxColor: 'blue',
			indexLabelFontColor: 'red',
			whiskerLength: 1,
			whiskerColor: '#BB2286',
			whiskerThickness: 1,
			indexLabelFontSize: 16,
			whiskerDashType : 'dash',
			lineThickness: 5,
			markerType: 'triangle', //none circle square triangle cross
			markerColor: '#008000',
			markerSize: 10,
			markerBorderColor: '#008000',
			markerBorderThickness: 4,
			showInLegend: true,
			legendText: '2005',
			legendMarkerBorderColor: '#008000',
			legendMarkerBorderThickness: 2,
			legendMarkerType: 'square',
			legendMarkerColor: 'red',
			risingColor: '#DD7E86',
			fallingColor: '#DD7E86',
			connectNullData: true,
			nullDataLineDashType:  'dot', //solid shortDash shortDot shortDashDot shortDashDotDot dot dash dashDot longDash longDashDot longDashDotDot	
			
			dataPoints: [
				{ x: new Date(2016, 2), y: 30000 },
				{ x: new Date(2016, 3), y: 35000 },
				{ x: new Date(2016, 4), y: 30000 },
				{ x: new Date(2016, 5), y: 30400 },
			]
		},
		{
			type: "splineArea", 
			showInLegend: true,
			yValueFormatString: "$#,##0",      
			name: "Maintenance",
			dataPoints: [
				{ x: new Date(2016, 2), y: 1700 },
				{ x: new Date(2016, 3), y: 2600 },
				{ x: new Date(2016, 4), y: 1000 },
				{ x: new Date(2016, 5), y: 1400 },
			]
		}
	]
});
		
    chart.render();
  
	function toggleDataSeries(e) {
		if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
			e.dataSeries.visible = false;
		} else {
			e.dataSeries.visible = true;
		}
		e.chart.render();
	}
	
  }
  
  
  </script>
  <div id="chartContainer" style="height: 300px; width: 100%;"></div>
